# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: service monitoring

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install requests
        pip install redis
    - name: service monitoring
      env: 
         DINGTALK_TOKEN: ${{ secrets.DINGTALK_TOKEN }}
         DDDDOCR_URL: ${{ secrets.DDDDOCR_URL }}
         REDIS_HOST: ${{ secrets.REDIS_HOST }}
         REDIS_PASS: ${{ secrets.REDIS_PASS }}
      run: |
        python run.py
